version: '3.7'

services:
  ruby:
    container_name: ruby-api
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./api:/api
    ports:
      - "3000:3000"
  front:
    container_name: vue-front
    image: node:lts-alpine
    working_dir: /home/myproject/front
    volumes:
      - ./front:/home/myproject/front
    ports:
      - "7000:8080"
    command: /bin/sh -c "[ -d node_modules ] && echo "up-to-date" || yarn && yarn serve"